/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Tugas;

import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.geom.GeneralPath;

public class Tugas3_PersegiEnam extends javax.swing.JInternalFrame {

    public static final int Canvas_Width=600;
    public static final int Canvas_Height=480;
    /**
     * Creates new form
     */
    public Tugas3_PersegiEnam() {
        initComponents();
        setPreferredSize(new Dimension(Canvas_Width,Canvas_Height));
    }
        @Override
        public void paintComponent(Graphics g){
        super.paintComponent(g);
        segitiga(g);
        }

    public void segitiga(Graphics g){
                setBackground(Color.WHITE);
                Graphics2D g2=(Graphics2D)g;
                g2.setPaint(Color.RED);
                double x[]={200,300,350,300,200,150};
                double y[]={350,350,250,150,150,250};
                
                GeneralPath p=new GeneralPath();
                p.moveTo(x[0],y[0]);
                for (int i = 1; i<x.length; i++){
                    p.lineTo(x[i],y[i]);
                }
                g2.fill(p);
            }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Persegi Enam");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jButton1)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jButton1)
                .addContainerGap(313, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Tugas3_PersegiEnam tiga= new Tugas3_PersegiEnam();
                setContentPane(tiga);
                repaint();
                tiga.setDefaultCloseOperation(PROPERTIES);
                tiga.pack();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
