/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ContohC;

import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Polygon;
import java.awt.geom.Rectangle2D;
import java.awt.geom.Ellipse2D;
import java.awt.geom.GeneralPath;

/**
 *
 * @author user
 */
public class Form3a extends javax.swing.JInternalFrame {
    
    public static final int Canvas_Width=600;
    public static final int Canvas_Height=480;
    private String jenis;
    
    /**
     * Creates new form Form3a
     */
    public Form3a() {
        initComponents();
        jenis="Kotak";
        setPreferredSize(new Dimension(Canvas_Width,Canvas_Height));
    }
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        switch(jenis){
            case "Kotak":
                kotak(g);
                break;
            
            case "Lingkaran":
                lingkaran(g);
                break;
            case "Segitiga":
                segitiga(g);
                break;
            case "Garis":
                garis(g);
                break;
                
        }
    }
    
        //membuat bangun datar kotak, lingkaran, segitiga, garis
            public void kotak(Graphics g){
                setBackground(Color.WHITE);
                Graphics2D g2=(Graphics2D)g;
                g2.setPaint(Color.MAGENTA);
                g2.draw(new Rectangle2D.Double(30,60,80,20));
                g2.fill(new Rectangle2D.Double(20,150,100,50));
                
            }
        public void lingkaran(Graphics g){
                setBackground(Color.YELLOW);
                Graphics2D g2=(Graphics2D)g;
                g2.setPaint(Color.CYAN);
                g2.draw(new Ellipse2D.Double(20,50,80,20));
                g2.fill(new Ellipse2D.Double(20,150,100,50));
                
            }
        public void segitiga(Graphics g){
                setBackground(Color.WHITE);
                Graphics2D g2=(Graphics2D)g;
                g2.setPaint(Color.GREEN);
                double x[]={183,72,45};
                double y[]={183,72,100};
                
                GeneralPath p=new GeneralPath();
                p.moveTo(x[0],y[0]);
                for (int i = 1; i<x.length; i++){
                    p.lineTo(x[i],y[i]);
                }
                g2.fill(p);
            }
            public void garis(Graphics g){
                setBackground(Color.WHITE);
                Graphics2D g2=(Graphics2D) g;
                g2.setPaint(Color.RED);
                double x[]={100,200,200,300,300,400,400,500,500,600};
                double y[]={300,300,150,150,300,300,50,50,300,300};
                
                GeneralPath p=new GeneralPath();
                p.moveTo(x[0], y[0]);
                for (int i=1;i<x.length;i++){
                p.lineTo(x[i],y[i]);
                }
                g2.draw(p);
            }
            
        
        
            
            
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Bidang datar GUI");

        jLabel2.setText("PILIH YANG MANA");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<None>", "Kotak", "Lingkaran", "Segitiga", "Garis" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addGap(57, 57, 57)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String pil;
        pil = (String)jComboBox1.getSelectedItem();
        switch(pil){
            case "Kotak":
                jenis="Kotak";
                Form3a tiga= new Form3a();
                setContentPane(tiga);
                repaint();
                tiga.setDefaultCloseOperation(PROPERTIES);
                tiga.pack();
                break;
                
            case "Lingkaran":
                jenis="Lingkaran";
                setContentPane(new Form3a());
                repaint();
                break;
            
            case "Segitiga":
                jenis="Segitiga";
                setContentPane(new Form3a());
                repaint();
                break;
             
            case "Garis":
                jenis="Garis";
                setContentPane(new Form3a());
                repaint();
                break;
        }
                
                
        
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

   
}
